### PR TITLE
Update Cargo.toml better link to https

### PR DESCRIPTION
**Pull request by szabgab**

### CODE REVIEW

**Comment by de-vri-es** [comment]
Good point. Thank you for the PR!

**Comment by de-vri-es** [comment]
Released as 0.2.8 :)

Thanks again!

**Comment by szabgab** [comment]
BTW I am building the [rust digger](https://rust-digger.code-maven.com/) to find these small improvements.

**Comment by de-vri-es** [comment]
Oh, interesting. Looks like a useful tool :)

**Pull request merged**
